// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'third_party/openac_mobile_app.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({required RustLibApi api}) {
    instance.initMockImpl(api: api);
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {}

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => -1383991712;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
        stem: 'mopro_flutter_bindings',
        ioDirectory: 'rust/target/release/',
        webPrefix: 'pkg/',
      );
}

abstract class RustLibApi extends BaseApi {
  Future<String> openacMobileAppBenchmarkResultsFormatSize({
    required BigInt bytes,
  });

  Future<String> openacMobileAppGenerateSharedBlinds({
    required String documentsPath,
  });

  Future<String> openacMobileAppGetCommWShared({
    required String documentsPath,
    required String circuitType,
  });

  Future<void> openacMobileAppInitApp();

  Future<String> openacMobileAppMoproHelloWorld();

  Future<ProofResult> openacMobileAppProveJwt({required String documentsPath});

  Future<ProofResult> openacMobileAppProveShow({required String documentsPath});

  Future<ProofResult> openacMobileAppReblindJwt({
    required String documentsPath,
  });

  Future<ProofResult> openacMobileAppReblindShow({
    required String documentsPath,
  });

  Future<BenchmarkResults> openacMobileAppRunCompleteBenchmark({
    required String documentsPath,
  });

  Future<String> openacMobileAppSetupJwtKeys({required String documentsPath});

  Future<String> openacMobileAppSetupShowKeys({required String documentsPath});

  Future<bool> openacMobileAppVerifyJwt({required String documentsPath});

  Future<bool> openacMobileAppVerifyShow({required String documentsPath});

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ZkProofError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ZkProofError;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_ZkProofErrorPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<String> openacMobileAppBenchmarkResultsFormatSize({
    required BigInt bytes,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_u_64(bytes, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 1,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppBenchmarkResultsFormatSizeConstMeta,
        argValues: [bytes],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppBenchmarkResultsFormatSizeConstMeta =>
      const TaskConstMeta(
        debugName: "benchmark_results_format_size",
        argNames: ["bytes"],
      );

  @override
  Future<String> openacMobileAppGenerateSharedBlinds({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 2,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppGenerateSharedBlindsConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppGenerateSharedBlindsConstMeta =>
      const TaskConstMeta(
        debugName: "generate_shared_blinds",
        argNames: ["documentsPath"],
      );

  @override
  Future<String> openacMobileAppGetCommWShared({
    required String documentsPath,
    required String circuitType,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          sse_encode_String(circuitType, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 3,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppGetCommWSharedConstMeta,
        argValues: [documentsPath, circuitType],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppGetCommWSharedConstMeta =>
      const TaskConstMeta(
        debugName: "get_comm_w_shared",
        argNames: ["documentsPath", "circuitType"],
      );

  @override
  Future<void> openacMobileAppInitApp() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 4,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_unit,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppInitAppConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppInitAppConstMeta =>
      const TaskConstMeta(debugName: "init_app", argNames: []);

  @override
  Future<String> openacMobileAppMoproHelloWorld() {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 5,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: null,
        ),
        constMeta: kOpenacMobileAppMoproHelloWorldConstMeta,
        argValues: [],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppMoproHelloWorldConstMeta =>
      const TaskConstMeta(debugName: "mopro_hello_world", argNames: []);

  @override
  Future<ProofResult> openacMobileAppProveJwt({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 6,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppProveJwtConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppProveJwtConstMeta =>
      const TaskConstMeta(debugName: "prove_jwt", argNames: ["documentsPath"]);

  @override
  Future<ProofResult> openacMobileAppProveShow({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 7,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppProveShowConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppProveShowConstMeta =>
      const TaskConstMeta(debugName: "prove_show", argNames: ["documentsPath"]);

  @override
  Future<ProofResult> openacMobileAppReblindJwt({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 8,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppReblindJwtConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppReblindJwtConstMeta => const TaskConstMeta(
    debugName: "reblind_jwt",
    argNames: ["documentsPath"],
  );

  @override
  Future<ProofResult> openacMobileAppReblindShow({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 9,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_proof_result,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppReblindShowConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppReblindShowConstMeta => const TaskConstMeta(
    debugName: "reblind_show",
    argNames: ["documentsPath"],
  );

  @override
  Future<BenchmarkResults> openacMobileAppRunCompleteBenchmark({
    required String documentsPath,
  }) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 10,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_benchmark_results,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppRunCompleteBenchmarkConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppRunCompleteBenchmarkConstMeta =>
      const TaskConstMeta(
        debugName: "run_complete_benchmark",
        argNames: ["documentsPath"],
      );

  @override
  Future<String> openacMobileAppSetupJwtKeys({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 11,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppSetupJwtKeysConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppSetupJwtKeysConstMeta =>
      const TaskConstMeta(
        debugName: "setup_jwt_keys",
        argNames: ["documentsPath"],
      );

  @override
  Future<String> openacMobileAppSetupShowKeys({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 12,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppSetupShowKeysConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppSetupShowKeysConstMeta =>
      const TaskConstMeta(
        debugName: "setup_show_keys",
        argNames: ["documentsPath"],
      );

  @override
  Future<bool> openacMobileAppVerifyJwt({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 13,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppVerifyJwtConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppVerifyJwtConstMeta =>
      const TaskConstMeta(debugName: "verify_jwt", argNames: ["documentsPath"]);

  @override
  Future<bool> openacMobileAppVerifyShow({required String documentsPath}) {
    return handler.executeNormal(
      NormalTask(
        callFfi: (port_) {
          final serializer = SseSerializer(generalizedFrbRustBinding);
          sse_encode_String(documentsPath, serializer);
          pdeCallFfi(
            generalizedFrbRustBinding,
            serializer,
            funcId: 14,
            port: port_,
          );
        },
        codec: SseCodec(
          decodeSuccessData: sse_decode_bool,
          decodeErrorData:
              sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError,
        ),
        constMeta: kOpenacMobileAppVerifyShowConstMeta,
        argValues: [documentsPath],
        apiImpl: this,
      ),
    );
  }

  TaskConstMeta get kOpenacMobileAppVerifyShowConstMeta => const TaskConstMeta(
    debugName: "verify_show",
    argNames: ["documentsPath"],
  );

  RustArcIncrementStrongCountFnType
  get rust_arc_increment_strong_count_ZkProofError => wire
      .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError;

  RustArcDecrementStrongCountFnType
  get rust_arc_decrement_strong_count_ZkProofError => wire
      .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError;

  @protected
  ZkProofError
  dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  ZkProofError
  dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    dynamic raw,
  ) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  BenchmarkResults dco_decode_benchmark_results(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 17)
      throw Exception('unexpected arr length: expect 17 but see ${arr.length}');
    return BenchmarkResults(
      jwtSetupMs: dco_decode_u_64(arr[0]),
      showSetupMs: dco_decode_u_64(arr[1]),
      generateBlindsMs: dco_decode_u_64(arr[2]),
      proveJwtMs: dco_decode_u_64(arr[3]),
      reblindJwtMs: dco_decode_u_64(arr[4]),
      proveShowMs: dco_decode_u_64(arr[5]),
      reblindShowMs: dco_decode_u_64(arr[6]),
      verifyJwtMs: dco_decode_u_64(arr[7]),
      verifyShowMs: dco_decode_u_64(arr[8]),
      jwtProvingKeyBytes: dco_decode_u_64(arr[9]),
      jwtVerifyingKeyBytes: dco_decode_u_64(arr[10]),
      showProvingKeyBytes: dco_decode_u_64(arr[11]),
      showVerifyingKeyBytes: dco_decode_u_64(arr[12]),
      jwtProofBytes: dco_decode_u_64(arr[13]),
      showProofBytes: dco_decode_u_64(arr[14]),
      jwtWitnessBytes: dco_decode_u_64(arr[15]),
      showWitnessBytes: dco_decode_u_64(arr[16]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  ProofResult dco_decode_proof_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return ProofResult(
      prepMs: dco_decode_u_64(arr[0]),
      proveMs: dco_decode_u_64(arr[1]),
      totalMs: dco_decode_u_64(arr[2]),
      proofSizeBytes: dco_decode_u_64(arr[3]),
      commWShared: dco_decode_String(arr[4]),
    );
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  ZkProofError
  sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  ZkProofError
  sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    SseDeserializer deserializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return ZkProofErrorImpl.frbInternalSseDecode(
      sse_decode_usize(deserializer),
      sse_decode_i_32(deserializer),
    );
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  BenchmarkResults sse_decode_benchmark_results(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_jwtSetupMs = sse_decode_u_64(deserializer);
    var var_showSetupMs = sse_decode_u_64(deserializer);
    var var_generateBlindsMs = sse_decode_u_64(deserializer);
    var var_proveJwtMs = sse_decode_u_64(deserializer);
    var var_reblindJwtMs = sse_decode_u_64(deserializer);
    var var_proveShowMs = sse_decode_u_64(deserializer);
    var var_reblindShowMs = sse_decode_u_64(deserializer);
    var var_verifyJwtMs = sse_decode_u_64(deserializer);
    var var_verifyShowMs = sse_decode_u_64(deserializer);
    var var_jwtProvingKeyBytes = sse_decode_u_64(deserializer);
    var var_jwtVerifyingKeyBytes = sse_decode_u_64(deserializer);
    var var_showProvingKeyBytes = sse_decode_u_64(deserializer);
    var var_showVerifyingKeyBytes = sse_decode_u_64(deserializer);
    var var_jwtProofBytes = sse_decode_u_64(deserializer);
    var var_showProofBytes = sse_decode_u_64(deserializer);
    var var_jwtWitnessBytes = sse_decode_u_64(deserializer);
    var var_showWitnessBytes = sse_decode_u_64(deserializer);
    return BenchmarkResults(
      jwtSetupMs: var_jwtSetupMs,
      showSetupMs: var_showSetupMs,
      generateBlindsMs: var_generateBlindsMs,
      proveJwtMs: var_proveJwtMs,
      reblindJwtMs: var_reblindJwtMs,
      proveShowMs: var_proveShowMs,
      reblindShowMs: var_reblindShowMs,
      verifyJwtMs: var_verifyJwtMs,
      verifyShowMs: var_verifyShowMs,
      jwtProvingKeyBytes: var_jwtProvingKeyBytes,
      jwtVerifyingKeyBytes: var_jwtVerifyingKeyBytes,
      showProvingKeyBytes: var_showProvingKeyBytes,
      showVerifyingKeyBytes: var_showVerifyingKeyBytes,
      jwtProofBytes: var_jwtProofBytes,
      showProofBytes: var_showProofBytes,
      jwtWitnessBytes: var_jwtWitnessBytes,
      showWitnessBytes: var_showWitnessBytes,
    );
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  ProofResult sse_decode_proof_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_prepMs = sse_decode_u_64(deserializer);
    var var_proveMs = sse_decode_u_64(deserializer);
    var var_totalMs = sse_decode_u_64(deserializer);
    var var_proofSizeBytes = sse_decode_u_64(deserializer);
    var var_commWShared = sse_decode_String(deserializer);
    return ProofResult(
      prepMs: var_prepMs,
      proveMs: var_proveMs,
      totalMs: var_totalMs,
      proofSizeBytes: var_proofSizeBytes,
      commWShared: var_commWShared,
    );
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  void
  sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    ZkProofError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ZkProofErrorImpl).frbInternalSseEncode(move: true),
      serializer,
    );
  }

  @protected
  void
  sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
    ZkProofError self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
      (self as ZkProofErrorImpl).frbInternalSseEncode(move: null),
      serializer,
    );
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_benchmark_results(
    BenchmarkResults self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.jwtSetupMs, serializer);
    sse_encode_u_64(self.showSetupMs, serializer);
    sse_encode_u_64(self.generateBlindsMs, serializer);
    sse_encode_u_64(self.proveJwtMs, serializer);
    sse_encode_u_64(self.reblindJwtMs, serializer);
    sse_encode_u_64(self.proveShowMs, serializer);
    sse_encode_u_64(self.reblindShowMs, serializer);
    sse_encode_u_64(self.verifyJwtMs, serializer);
    sse_encode_u_64(self.verifyShowMs, serializer);
    sse_encode_u_64(self.jwtProvingKeyBytes, serializer);
    sse_encode_u_64(self.jwtVerifyingKeyBytes, serializer);
    sse_encode_u_64(self.showProvingKeyBytes, serializer);
    sse_encode_u_64(self.showVerifyingKeyBytes, serializer);
    sse_encode_u_64(self.jwtProofBytes, serializer);
    sse_encode_u_64(self.showProofBytes, serializer);
    sse_encode_u_64(self.jwtWitnessBytes, serializer);
    sse_encode_u_64(self.showWitnessBytes, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  ) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_proof_result(ProofResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self.prepMs, serializer);
    sse_encode_u_64(self.proveMs, serializer);
    sse_encode_u_64(self.totalMs, serializer);
    sse_encode_u_64(self.proofSizeBytes, serializer);
    sse_encode_String(self.commWShared, serializer);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }
}

@sealed
class ZkProofErrorImpl extends RustOpaque implements ZkProofError {
  // Not to be used by end users
  ZkProofErrorImpl.frbInternalDcoDecode(List<dynamic> wire)
    : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  ZkProofErrorImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
    : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_ZkProofError,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZkProofError,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_ZkProofErrorPtr,
  );
}
