// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};
use openac_mobile_app::*;

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.11.1";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = -1383991712;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__openac_mobile_app__benchmark_results_format_size_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "benchmark_results_format_size",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_bytes = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(
                        openac_mobile_app::BenchmarkResults::format_size(api_bytes),
                    )?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__generate_shared_blinds_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "generate_shared_blinds",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::generate_shared_blinds(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__get_comm_w_shared_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "get_comm_w_shared",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            let api_circuit_type = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok =
                        openac_mobile_app::get_comm_w_shared(api_documents_path, api_circuit_type)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        openac_mobile_app::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__mopro_hello_world_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "mopro_hello_world",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok(openac_mobile_app::mopro_hello_world())?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__prove_jwt_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prove_jwt",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::prove_jwt(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__prove_show_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "prove_show",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::prove_show(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__reblind_jwt_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reblind_jwt",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::reblind_jwt(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__reblind_show_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "reblind_show",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::reblind_show(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__run_complete_benchmark_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "run_complete_benchmark",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::run_complete_benchmark(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__setup_jwt_keys_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "setup_jwt_keys",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::setup_jwt_keys(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__setup_show_keys_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "setup_show_keys",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::setup_show_keys(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__verify_jwt_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verify_jwt",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::verify_jwt(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}
fn wire__openac_mobile_app__verify_show_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "verify_show",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_documents_path = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ZkProofError>((move || {
                    let output_ok = openac_mobile_app::verify_show(api_documents_path)?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: static_checks

#[allow(clippy::unnecessary_literal_unwrap)]
const _: fn() = || {
    {
        let BenchmarkResults = None::<openac_mobile_app::BenchmarkResults>.unwrap();
        let _: u64 = BenchmarkResults.jwt_setup_ms;
        let _: u64 = BenchmarkResults.show_setup_ms;
        let _: u64 = BenchmarkResults.generate_blinds_ms;
        let _: u64 = BenchmarkResults.prove_jwt_ms;
        let _: u64 = BenchmarkResults.reblind_jwt_ms;
        let _: u64 = BenchmarkResults.prove_show_ms;
        let _: u64 = BenchmarkResults.reblind_show_ms;
        let _: u64 = BenchmarkResults.verify_jwt_ms;
        let _: u64 = BenchmarkResults.verify_show_ms;
        let _: u64 = BenchmarkResults.jwt_proving_key_bytes;
        let _: u64 = BenchmarkResults.jwt_verifying_key_bytes;
        let _: u64 = BenchmarkResults.show_proving_key_bytes;
        let _: u64 = BenchmarkResults.show_verifying_key_bytes;
        let _: u64 = BenchmarkResults.jwt_proof_bytes;
        let _: u64 = BenchmarkResults.show_proof_bytes;
        let _: u64 = BenchmarkResults.jwt_witness_bytes;
        let _: u64 = BenchmarkResults.show_witness_bytes;
    }
    {
        let ProofResult = None::<openac_mobile_app::ProofResult>.unwrap();
        let _: u64 = ProofResult.prep_ms;
        let _: u64 = ProofResult.prove_ms;
        let _: u64 = ProofResult.total_ms;
        let _: u64 = ProofResult.proof_size_bytes;
        let _: String = ProofResult.comm_w_shared;
    }
};

// Section: related_funcs

flutter_rust_bridge::frb_generated_moi_arc_impl_value!(
    flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>
);

// Section: dart2rust

impl SseDecode for ZkProofError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <RustOpaqueMoi<
            flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>,
        >>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::rust_auto_opaque_decode_owned(inner);
    }
}

impl SseDecode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <usize>::sse_decode(deserializer);
        return decode_rust_opaque_moi(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for openac_mobile_app::BenchmarkResults {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_jwtSetupMs = <u64>::sse_decode(deserializer);
        let mut var_showSetupMs = <u64>::sse_decode(deserializer);
        let mut var_generateBlindsMs = <u64>::sse_decode(deserializer);
        let mut var_proveJwtMs = <u64>::sse_decode(deserializer);
        let mut var_reblindJwtMs = <u64>::sse_decode(deserializer);
        let mut var_proveShowMs = <u64>::sse_decode(deserializer);
        let mut var_reblindShowMs = <u64>::sse_decode(deserializer);
        let mut var_verifyJwtMs = <u64>::sse_decode(deserializer);
        let mut var_verifyShowMs = <u64>::sse_decode(deserializer);
        let mut var_jwtProvingKeyBytes = <u64>::sse_decode(deserializer);
        let mut var_jwtVerifyingKeyBytes = <u64>::sse_decode(deserializer);
        let mut var_showProvingKeyBytes = <u64>::sse_decode(deserializer);
        let mut var_showVerifyingKeyBytes = <u64>::sse_decode(deserializer);
        let mut var_jwtProofBytes = <u64>::sse_decode(deserializer);
        let mut var_showProofBytes = <u64>::sse_decode(deserializer);
        let mut var_jwtWitnessBytes = <u64>::sse_decode(deserializer);
        let mut var_showWitnessBytes = <u64>::sse_decode(deserializer);
        return openac_mobile_app::BenchmarkResults {
            jwt_setup_ms: var_jwtSetupMs,
            show_setup_ms: var_showSetupMs,
            generate_blinds_ms: var_generateBlindsMs,
            prove_jwt_ms: var_proveJwtMs,
            reblind_jwt_ms: var_reblindJwtMs,
            prove_show_ms: var_proveShowMs,
            reblind_show_ms: var_reblindShowMs,
            verify_jwt_ms: var_verifyJwtMs,
            verify_show_ms: var_verifyShowMs,
            jwt_proving_key_bytes: var_jwtProvingKeyBytes,
            jwt_verifying_key_bytes: var_jwtVerifyingKeyBytes,
            show_proving_key_bytes: var_showProvingKeyBytes,
            show_verifying_key_bytes: var_showVerifyingKeyBytes,
            jwt_proof_bytes: var_jwtProofBytes,
            show_proof_bytes: var_showProofBytes,
            jwt_witness_bytes: var_jwtWitnessBytes,
            show_witness_bytes: var_showWitnessBytes,
        };
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for openac_mobile_app::ProofResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_prepMs = <u64>::sse_decode(deserializer);
        let mut var_proveMs = <u64>::sse_decode(deserializer);
        let mut var_totalMs = <u64>::sse_decode(deserializer);
        let mut var_proofSizeBytes = <u64>::sse_decode(deserializer);
        let mut var_commWShared = <String>::sse_decode(deserializer);
        return openac_mobile_app::ProofResult {
            prep_ms: var_prepMs,
            prove_ms: var_proveMs,
            total_ms: var_totalMs,
            proof_size_bytes: var_proofSizeBytes,
            comm_w_shared: var_commWShared,
        };
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        1 => wire__openac_mobile_app__benchmark_results_format_size_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        2 => {
            wire__openac_mobile_app__generate_shared_blinds_impl(port, ptr, rust_vec_len, data_len)
        }
        3 => wire__openac_mobile_app__get_comm_w_shared_impl(port, ptr, rust_vec_len, data_len),
        4 => wire__openac_mobile_app__init_app_impl(port, ptr, rust_vec_len, data_len),
        5 => wire__openac_mobile_app__mopro_hello_world_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__openac_mobile_app__prove_jwt_impl(port, ptr, rust_vec_len, data_len),
        7 => wire__openac_mobile_app__prove_show_impl(port, ptr, rust_vec_len, data_len),
        8 => wire__openac_mobile_app__reblind_jwt_impl(port, ptr, rust_vec_len, data_len),
        9 => wire__openac_mobile_app__reblind_show_impl(port, ptr, rust_vec_len, data_len),
        10 => {
            wire__openac_mobile_app__run_complete_benchmark_impl(port, ptr, rust_vec_len, data_len)
        }
        11 => wire__openac_mobile_app__setup_jwt_keys_impl(port, ptr, rust_vec_len, data_len),
        12 => wire__openac_mobile_app__setup_show_keys_impl(port, ptr, rust_vec_len, data_len),
        13 => wire__openac_mobile_app__verify_jwt_impl(port, ptr, rust_vec_len, data_len),
        14 => wire__openac_mobile_app__verify_show_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<ZkProofError> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self.0)
            .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive for FrbWrapper<ZkProofError> {}

impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<ZkProofError>> for ZkProofError {
    fn into_into_dart(self) -> FrbWrapper<ZkProofError> {
        self.into()
    }
}

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<openac_mobile_app::BenchmarkResults> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.jwt_setup_ms.into_into_dart().into_dart(),
            self.0.show_setup_ms.into_into_dart().into_dart(),
            self.0.generate_blinds_ms.into_into_dart().into_dart(),
            self.0.prove_jwt_ms.into_into_dart().into_dart(),
            self.0.reblind_jwt_ms.into_into_dart().into_dart(),
            self.0.prove_show_ms.into_into_dart().into_dart(),
            self.0.reblind_show_ms.into_into_dart().into_dart(),
            self.0.verify_jwt_ms.into_into_dart().into_dart(),
            self.0.verify_show_ms.into_into_dart().into_dart(),
            self.0.jwt_proving_key_bytes.into_into_dart().into_dart(),
            self.0.jwt_verifying_key_bytes.into_into_dart().into_dart(),
            self.0.show_proving_key_bytes.into_into_dart().into_dart(),
            self.0.show_verifying_key_bytes.into_into_dart().into_dart(),
            self.0.jwt_proof_bytes.into_into_dart().into_dart(),
            self.0.show_proof_bytes.into_into_dart().into_dart(),
            self.0.jwt_witness_bytes.into_into_dart().into_dart(),
            self.0.show_witness_bytes.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<openac_mobile_app::BenchmarkResults>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<openac_mobile_app::BenchmarkResults>>
    for openac_mobile_app::BenchmarkResults
{
    fn into_into_dart(self) -> FrbWrapper<openac_mobile_app::BenchmarkResults> {
        self.into()
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for FrbWrapper<openac_mobile_app::ProofResult> {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.0.prep_ms.into_into_dart().into_dart(),
            self.0.prove_ms.into_into_dart().into_dart(),
            self.0.total_ms.into_into_dart().into_dart(),
            self.0.proof_size_bytes.into_into_dart().into_dart(),
            self.0.comm_w_shared.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for FrbWrapper<openac_mobile_app::ProofResult>
{
}
impl flutter_rust_bridge::IntoIntoDart<FrbWrapper<openac_mobile_app::ProofResult>>
    for openac_mobile_app::ProofResult
{
    fn into_into_dart(self) -> FrbWrapper<openac_mobile_app::ProofResult> {
        self.into()
    }
}

impl SseEncode for ZkProofError {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>>>::sse_encode(flutter_rust_bridge::for_generated::rust_auto_opaque_encode::<_, MoiArc<_>>(self), serializer);
    }
}

impl SseEncode
    for RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>>
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        let (ptr, size) = self.sse_encode_raw();
        <usize>::sse_encode(ptr, serializer);
        <i32>::sse_encode(size, serializer);
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for openac_mobile_app::BenchmarkResults {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.jwt_setup_ms, serializer);
        <u64>::sse_encode(self.show_setup_ms, serializer);
        <u64>::sse_encode(self.generate_blinds_ms, serializer);
        <u64>::sse_encode(self.prove_jwt_ms, serializer);
        <u64>::sse_encode(self.reblind_jwt_ms, serializer);
        <u64>::sse_encode(self.prove_show_ms, serializer);
        <u64>::sse_encode(self.reblind_show_ms, serializer);
        <u64>::sse_encode(self.verify_jwt_ms, serializer);
        <u64>::sse_encode(self.verify_show_ms, serializer);
        <u64>::sse_encode(self.jwt_proving_key_bytes, serializer);
        <u64>::sse_encode(self.jwt_verifying_key_bytes, serializer);
        <u64>::sse_encode(self.show_proving_key_bytes, serializer);
        <u64>::sse_encode(self.show_verifying_key_bytes, serializer);
        <u64>::sse_encode(self.jwt_proof_bytes, serializer);
        <u64>::sse_encode(self.show_proof_bytes, serializer);
        <u64>::sse_encode(self.jwt_witness_bytes, serializer);
        <u64>::sse_encode(self.show_witness_bytes, serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for openac_mobile_app::ProofResult {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u64>::sse_encode(self.prep_ms, serializer);
        <u64>::sse_encode(self.prove_ms, serializer);
        <u64>::sse_encode(self.total_ms, serializer);
        <u64>::sse_encode(self.proof_size_bytes, serializer);
        <String>::sse_encode(self.comm_w_shared, serializer);
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};
    use openac_mobile_app::*;

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_mopro_flutter_bindings_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>>::increment_strong_count(ptr as _);
    }

    #[unsafe(no_mangle)]
    pub extern "C" fn frbgen_mopro_flutter_bindings_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.11.1.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};
    use openac_mobile_app::*;

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();

    #[wasm_bindgen]
    pub fn rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>>::increment_strong_count(ptr as _);
    }

    #[wasm_bindgen]
    pub fn rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerZkProofError(
        ptr: *const std::ffi::c_void,
    ) {
        MoiArc::<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ZkProofError>>::decrement_strong_count(ptr as _);
    }
}
#[cfg(target_family = "wasm")]
pub use web::*;
