@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "*domain*",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "*Dto;*Mapper;*Properties",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": false,
    "showMethods": false,
    "showMethodParameterNames": false,
    "showMethodParameterTypes": false,
    "showMethodReturnType": false,
    "showPackageLevels": 5,
    "showDetailedClassStructure": false
  },
  "rootClass": "ch.admin.bj.swiyu.issuer.infrastructure.web.management.CredentialManagementController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_92668751 { 
   	label=admin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_969162937 { 
   	label=bj
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1256842502 { 
   	label=swiyu
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_297046061 { 
   	label=issuer
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   subgraph cluster_1073771132 { 
   	label=infrastructure
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   CredentialManagementController1123570110[
	label="(C)CredentialManagementController"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_857347596 { 
   	label=service
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   CredentialManagementService354864683[
	label="(C)CredentialManagementService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

CredentialOfferValidationService354864683[
	label="(C)CredentialOfferValidationService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

CredentialPersistenceService540401500[
	label="(C)CredentialPersistenceService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

CredentialStateService354864683[
	label="(C)CredentialStateService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

DataIntegrityService354864683[
	label="(C)DataIntegrityService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

StatusListOrchestrator1693355827[
	label="(C)StatusListOrchestrator"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

StatusListPersistenceService1693355827[
	label="(C)StatusListPersistenceService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

StatusListSigningService1693355827[
	label="(C)StatusListSigningService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

StatusListValidator1693355827[
	label="(C)StatusListValidator"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];

StatusRegistryClient1498629038[
	label="(C)StatusRegistryClient"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 
} 
} 
} 
} 

'edges    
CredentialManagementController1123570110 -> CredentialManagementService354864683[label="credentialManagementService
[0..1]"];
CredentialManagementService354864683 -> CredentialOfferValidationService354864683[label="validationService
[0..1]"];
CredentialManagementService354864683 -> CredentialPersistenceService540401500[label="persistenceService
[0..1]"];
CredentialManagementService354864683 -> CredentialStateService354864683[label="stateService
[0..1]"];
CredentialManagementService354864683 -> StatusListOrchestrator1693355827[label="statusListOrchestrator
[0..1]"];
CredentialOfferValidationService354864683 -> DataIntegrityService354864683[label="dataIntegrityService
[0..1]"];
CredentialStateService354864683 -> CredentialPersistenceService540401500[label="persistenceService
[0..1]"];
CredentialStateService354864683 -> StatusListPersistenceService1693355827[label="statusListPersistenceService
[0..1]"];
StatusListOrchestrator1693355827 -> StatusListSigningService1693355827[label="signingService
[0..1]"];
StatusListOrchestrator1693355827 -> StatusListValidator1693355827[label="resolveAndValidateStatusLists() -> requireAllStatusListsResolved()"];
StatusListOrchestrator1693355827 -> StatusRegistryClient1498629038[label="statusRegistryClient
[0..1]"];
    
}
@enduml