

application:
  signing_key: "-----BEGIN EC PRIVATE KEY-----\nMHcCAQEEIGYpEuy/ijtVu+QOIsmXiK9HNPQ0bkBX+wvhaFAh/zoKoAoGCCqGSM49\nAwEHoUQDQgAEoqBwmYd3RAHs+sFe/U7UFTXbkWmPAaqKTHCvsV8tvxWeng+OkMo1\n8QOT2rDNk+qMBrCJnyyiRU6jMdH4q3z1Pg==\n-----END EC PRIVATE KEY-----\n"
  signing-key-verification-method: "did:example:12345#key-1"
  external-url: "http://${server.host}:${server.port}"
  client-metadata-file: "classpath:client_metadata.json"

spring:
  docker:
    compose:
      enabled: true
      file: compose.yaml
  datasource:
    url: "jdbc:postgresql://localhost:5434/verifier_db"
    username: "verifier_user"
    password: "secret"
    driver-class-name: org.postgresql.Driver
  mvc:
    log-resolved-exception: false # see https://stackoverflow.com/a/77147791
  jpa:
    hibernate:
      ddl-auto: validate

logging:
  level:
    ch.admin.bj.swiyu: DEBUG

springdoc:
  show-actuator: true