@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "*Dto;*Mapper;*Properties",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 3,
    "backwardDepth": 3,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": false,
    "showMethods": false,
    "showMethodParameterNames": false,
    "showMethodParameterTypes": false,
    "showMethodReturnType": false,
    "showPackageLevels": 5,
    "showDetailedClassStructure": false
  },
  "rootClass": "ch.admin.bj.swiyu.issuer.infrastructure.web.signer.CredentialMetadataController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_92668751 { 
   	label=admin
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_969162937 { 
   	label=bj
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   subgraph cluster_1256842502 { 
   	label=swiyu
	labeljust=l
	fillcolor="#c4c4c4"
	style=filled
   
   subgraph cluster_297046061 { 
   	label=issuer
	labeljust=l
	fillcolor="#bababa"
	style=filled
   
   subgraph cluster_1073771132 { 
   	label=infrastructure
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   CredentialMetadataController281199067[
	label="(C)CredentialMetadataController"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_2045824421 { 
   	label=domain
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   CredentialMetadata314384712[
	label="(C)CredentialMetadata"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 

subgraph cluster_857347596 { 
   	label=service
	labeljust=l
	fillcolor="#b0b0b0"
	style=filled
   
   CredentialMetadataService354864683[
	label="(C)CredentialMetadataService"
	style=filled
	shape=rect
	fillcolor="#FFFFFF"
];
} 
} 
} 
} 
} 

'edges    
CredentialMetadataController281199067 -> CredentialMetadataService354864683[label="credentialMetadataService
[0..1]"];
CredentialMetadataService354864683 -> CredentialMetadata314384712[label="credentialMetadata
[0..1]"];
    
}
@enduml