package ch.admin.foitt.wallet.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.runtime.Immutable
import androidx.compose.runtime.Stable
import androidx.compose.ui.graphics.Color

@Immutable
data class WalletColorScheme(
    val primary: Color,
    val onPrimary: Color,
    val primaryContainer: Color,
    val onPrimaryContainer: Color,
    val inversePrimary: Color,
    val secondary: Color,
    val onSecondary: Color,
    val secondaryContainer: Color,
    val onSecondaryContainer: Color,
    val tertiary: Color,
    val onTertiary: Color,
    val tertiaryContainer: Color,
    val onTertiaryContainer: Color,
    val background: Color,
    val onBackground: Color,
    val surface: Color,
    val onSurface: Color,
    val surfaceVariant: Color,
    val onSurfaceVariant: Color,
    val surfaceTint: Color,
    val inverseSurface: Color,
    val inverseOnSurface: Color,
    val error: Color,
    val onError: Color,
    val errorContainer: Color,
    val onErrorContainer: Color,
    val outline: Color,
    val outlineVariant: Color,
    val scrim: Color,
    val surfaceBright: Color,
    val surfaceDim: Color,
    val surfaceContainer: Color,
    val surfaceContainerHigh: Color,
    val surfaceContainerHighest: Color,
    val surfaceContainerLow: Color,
    val surfaceContainerLowest: Color,

    // Custom theme colors
    val shaderTransparent: Color,
    val onShaderTransparent: Color,
    val lightPrimary: Color,
    val onLightPrimary: Color,
    val lightTertiary: Color,
    val onLightTertiary: Color,
    val lightError: Color,
    val onLightError: Color,
    val lightOrange: Color,
    val onLightOrange: Color,
    val surfaceTransparentFixed: Color,
    val onGradientFixed: Color,
    val primaryBackgroundFixed: Color,
    val primaryFixed: Color,
    val onPrimaryFixed: Color,
    val secondaryFixed: Color,
    val onSecondaryFixed: Color,
    val secondaryContainerFixed: Color,
    val onSecondaryContainerFixed: Color,
    val onSurfaceFixed: Color,
    val onSurfaceVariantFixed: Color,
    val errorFixed: Color,
    val lightErrorFixed: Color,
    val onLightErrorFixed: Color,
    val onWhiteTransparentFixed: Color,

    val sensitiveBadge: Color,
    val onSensitiveBadge: Color,

    val errorBackgroundLight: Color,
    val errorBackgroundDark: Color,

    val listItemBackground: Color,

    val inactiveOverlay: Color,

    val progressTrackColor: Color,
) {
    @Stable
    internal val materialColorScheme: ColorScheme by lazy {
        ColorScheme(
            primary = primary,
            onPrimary = onPrimary,
            primaryContainer = primaryContainer,
            onPrimaryContainer = onPrimaryContainer,
            inversePrimary = inversePrimary,
            secondary = secondary,
            onSecondary = onSecondary,
            secondaryContainer = secondaryContainer,
            onSecondaryContainer = onSecondaryContainer,
            tertiary = tertiary,
            onTertiary = onTertiary,
            tertiaryContainer = tertiaryContainer,
            onTertiaryContainer = onTertiaryContainer,
            background = background,
            onBackground = onBackground,
            surface = surface,
            onSurface = onSurface,
            surfaceVariant = surfaceVariant,
            onSurfaceVariant = onSurfaceVariant,
            surfaceTint = surfaceTint,
            inverseSurface = inverseSurface,
            inverseOnSurface = inverseOnSurface,
            error = error,
            onError = onError,
            errorContainer = errorContainer,
            onErrorContainer = onErrorContainer,
            outline = outline,
            outlineVariant = outlineVariant,
            scrim = scrim,
            surfaceBright = surfaceBright,
            surfaceDim = surfaceDim,
            surfaceContainer = surfaceContainer,
            surfaceContainerHigh = surfaceContainerHigh,
            surfaceContainerHighest = surfaceContainerHighest,
            surfaceContainerLow = surfaceContainerLow,
            surfaceContainerLowest = surfaceContainerLowest,
            primaryFixed = primaryFixed,
            primaryFixedDim = primaryFixed,
            onPrimaryFixed = onPrimaryFixed,
            onPrimaryFixedVariant = onPrimaryFixed,
            secondaryFixed = secondaryFixed,
            secondaryFixedDim = secondaryFixed,
            onSecondaryFixed = onSecondaryFixed,
            onSecondaryFixedVariant = onSecondaryFixed,
            tertiaryFixed = tertiary,
            tertiaryFixedDim = tertiary,
            onTertiaryFixed = onTertiary,
            onTertiaryFixedVariant = onTertiary,
        )
    }

    companion object {
        @Stable
        internal val light by lazy {
            WalletColorScheme(
                primary = WalletColors.blue15,
                onPrimary = WalletColors.white,
                primaryContainer = WalletColors.blue50,
                onPrimaryContainer = WalletColors.blue90,
                inversePrimary = WalletColors.blue80,
                secondary = WalletColors.blue45,
                onSecondary = WalletColors.white,
                secondaryContainer = WalletColors.grey90,
                onSecondaryContainer = WalletColors.grey30,
                tertiary = WalletColors.green35,
                onTertiary = WalletColors.white,
                tertiaryContainer = WalletColors.green50,
                onTertiaryContainer = WalletColors.white,
                background = WalletColors.white,
                onBackground = WalletColors.grey10,
                surface = WalletColors.white,
                onSurface = WalletColors.blue15,
                surfaceVariant = Color.Unspecified,
                onSurfaceVariant = WalletColors.grey30,
                surfaceTint = Color.Unspecified,
                inverseSurface = WalletColors.grey20,
                inverseOnSurface = WalletColors.grey95,
                error = WalletColors.red40,
                onError = WalletColors.white,
                errorContainer = WalletColors.red50,
                onErrorContainer = WalletColors.white,
                outline = WalletColors.grey50,
                outlineVariant = WalletColors.grey80,
                scrim = WalletColors.transparentBlack01,
                surfaceBright = WalletColors.white,
                surfaceDim = WalletColors.grey87,
                surfaceContainer = WalletColors.grey94,
                surfaceContainerHigh = WalletColors.grey92,
                surfaceContainerHighest = WalletColors.grey90,
                surfaceContainerLow = WalletColors.grey96,
                surfaceContainerLowest = WalletColors.white,

                shaderTransparent = WalletColors.transparentWhite01,
                onShaderTransparent = WalletColors.white,
                lightPrimary = WalletColors.blue95,
                onLightPrimary = WalletColors.blue15,
                lightTertiary = WalletColors.green98,
                onLightTertiary = WalletColors.green35,
                lightError = WalletColors.red95,
                onLightError = WalletColors.red40,
                lightOrange = WalletColors.orange95,
                onLightOrange = WalletColors.orange50,
                surfaceTransparentFixed = WalletColors.transparentBlack02,
                onGradientFixed = WalletColors.white,
                primaryBackgroundFixed = WalletColors.blue10,
                primaryFixed = WalletColors.blue15,
                onPrimaryFixed = WalletColors.white,
                secondaryFixed = WalletColors.grey90,
                onSecondaryFixed = WalletColors.grey10,
                secondaryContainerFixed = WalletColors.grey90,
                onSecondaryContainerFixed = WalletColors.grey30,
                onSurfaceFixed = WalletColors.grey10,
                onSurfaceVariantFixed = WalletColors.grey30,
                errorFixed = WalletColors.red40,
                lightErrorFixed = WalletColors.red95,
                onLightErrorFixed = WalletColors.red40,
                onWhiteTransparentFixed = WalletColors.white,

                errorBackgroundLight = WalletColors.red49,
                errorBackgroundDark = WalletColors.red16,

                listItemBackground = WalletColors.white,
                sensitiveBadge = WalletColors.purple91,
                onSensitiveBadge = WalletColors.purple27,
                inactiveOverlay = WalletColors.transparentWhite03,
                progressTrackColor = WalletColors.accentPurple,
            )
        }

        @Stable
        internal val dark by lazy {
            WalletColorScheme(
                primary = WalletColors.blue80,
                onPrimary = WalletColors.blue20,
                primaryContainer = WalletColors.blue30,
                onPrimaryContainer = WalletColors.blue70,
                inversePrimary = WalletColors.blue40,
                secondary = WalletColors.grey60,
                onSecondary = WalletColors.grey20,
                secondaryContainer = WalletColors.grey25,
                onSecondaryContainer = WalletColors.grey90,
                tertiary = WalletColors.green80,
                onTertiary = WalletColors.green20,
                tertiaryContainer = WalletColors.green30,
                onTertiaryContainer = WalletColors.green90,
                background = WalletColors.grey06,
                onBackground = WalletColors.grey90,
                surface = WalletColors.grey06,
                onSurface = WalletColors.white,
                surfaceVariant = Color.Unspecified,
                onSurfaceVariant = WalletColors.grey80,
                surfaceTint = Color.Unspecified,
                inverseSurface = WalletColors.grey90,
                inverseOnSurface = WalletColors.grey20,
                error = WalletColors.red80,
                onError = WalletColors.red20,
                errorContainer = WalletColors.red40,
                onErrorContainer = WalletColors.white,
                outline = WalletColors.grey60,
                outlineVariant = WalletColors.grey30,
                scrim = WalletColors.transparentBlack01,
                surfaceBright = WalletColors.grey24,
                surfaceDim = WalletColors.grey06,
                surfaceContainer = WalletColors.grey12,
                surfaceContainerHigh = WalletColors.grey17,
                surfaceContainerHighest = WalletColors.grey22,
                surfaceContainerLow = WalletColors.grey10,
                surfaceContainerLowest = WalletColors.grey04,

                shaderTransparent = WalletColors.transparentBlack01,
                onShaderTransparent = WalletColors.black,
                lightPrimary = WalletColors.blue15,
                onLightPrimary = WalletColors.blue80,
                lightTertiary = WalletColors.green08,
                onLightTertiary = WalletColors.green80,
                lightError = WalletColors.red15,
                onLightError = WalletColors.red80,
                lightOrange = WalletColors.orange15,
                onLightOrange = WalletColors.orange80,
                surfaceTransparentFixed = WalletColors.transparentBlack02,
                onGradientFixed = WalletColors.white,
                primaryBackgroundFixed = WalletColors.blue10,
                primaryFixed = WalletColors.blue15,
                onPrimaryFixed = WalletColors.white,
                secondaryFixed = WalletColors.grey90,
                onSecondaryFixed = WalletColors.grey10,
                secondaryContainerFixed = WalletColors.grey90,
                onSecondaryContainerFixed = WalletColors.grey30,
                onSurfaceFixed = WalletColors.grey10,
                onSurfaceVariantFixed = WalletColors.grey30,
                errorFixed = WalletColors.red40,
                lightErrorFixed = WalletColors.red95,
                onLightErrorFixed = WalletColors.red40,
                onWhiteTransparentFixed = WalletColors.white,

                errorBackgroundLight = WalletColors.red49,
                errorBackgroundDark = WalletColors.red16,

                listItemBackground = WalletColors.grey17,
                sensitiveBadge = WalletColors.purple18,
                onSensitiveBadge = WalletColors.purple91,
                inactiveOverlay = WalletColors.tansparentBlack03,

                progressTrackColor = WalletColors.accentBlueDark,
            )
        }
    }
}
