/* tslint:disable */
/* eslint-disable */

/**
 * Compare comm_W_shared between two instances (use verify() instead)
 */
export function compare_comm_w_shared(instance1_bytes: Uint8Array, instance2_bytes: Uint8Array): boolean;

/**
 * Initialize panic hook for better error messages in WASM
 */
export function init(): void;

/**
 * Prove the Prepare circuit and return proof/instance/witness for storage.
 * This is called once when a credential is added to the wallet.
 * The results should be stored and reused for each presentation via `present()`.
 *
 * Arguments:
 * - `pk_bytes`: Serialized Prepare proving key (from setup())
 *
 * Returns: PrecomputeResult { proof, instance, witness } — all as serialized bytes
 */
export function precompute(pk_bytes: Uint8Array): any;

/**
 * Prove the Prepare circuit using externally generated witness bytes.
 * This is used when witness is generated by TypeScript WitnessCalculator.
 *
 * Arguments:
 * - `pk_bytes`: Serialized Prepare proving key (from setup())
 * - `witness_wtns_bytes`: Circom WTNS binary witness (from TypeScript WitnessCalculator)
 *
 * Returns: PrecomputeResult { proof, instance, witness } — all as serialized bytes
 */
export function precompute_from_witness(pk_bytes: Uint8Array, witness_wtns_bytes: Uint8Array): any;

/**
 * Prove the Show circuit using externally generated witness bytes.
 * This is used when witness is generated by TypeScript WitnessCalculator.
 *
 * Arguments:
 * - `pk_bytes`: Serialized Show proving key (from setup())
 * - `witness_wtns_bytes`: Circom WTNS binary witness (from TypeScript WitnessCalculator)
 *
 * Returns: PrecomputeResult { proof, instance, witness } — all as serialized bytes
 */
export function precompute_show_from_witness(pk_bytes: Uint8Array, witness_wtns_bytes: Uint8Array): any;

/**
 * Execute a full presentation: generate shared blinds and reblind both the
 * Prepare and Show proofs using the same randomness.
 *
 * This is called each time the holder presents to a verifier. Both circuits
 * must already be proved (via the TypeScript WitnessCalculator + prove path).
 * This function generates fresh shared blinds and reblinds both proofs to
 * ensure unlinkability while maintaining cryptographic linkage (comm_W_shared).
 *
 * Arguments:
 * - `prepare_pk_bytes`:       Serialized Prepare proving key
 * - `prepare_instance_bytes`: Serialized Prepare instance (from prove step)
 * - `prepare_witness_bytes`:  Serialized Prepare witness (from prove step)
 * - `show_pk_bytes`:          Serialized Show proving key
 * - `show_instance_bytes`:    Serialized Show instance (from prove step)
 * - `show_witness_bytes`:     Serialized Show witness (from prove step)
 *
 * Returns: PresentResult { prepare_proof, prepare_instance, show_proof, show_instance }
 */
export function present(prepare_pk_bytes: Uint8Array, prepare_instance_bytes: Uint8Array, prepare_witness_bytes: Uint8Array, show_pk_bytes: Uint8Array, show_instance_bytes: Uint8Array, show_witness_bytes: Uint8Array): any;

/**
 * Setup both Prepare and Show circuit keys in a single call.
 * Returns serialized SetupResult with proving and verifying keys for both circuits.
 */
export function setup(): any;

/**
 * Setup Prepare circuit keys only (use setup() instead)
 */
export function setup_prepare(): any;

/**
 * Setup Show circuit keys only (use setup() instead)
 */
export function setup_show(): any;

/**
 * Complete verification: verify both Prepare and Show proofs and compare their
 * shared commitments (comm_W_shared) to ensure they use the same private data.
 *
 * Arguments:
 * - `prepare_proof_bytes`:    Serialized Prepare proof (from present())
 * - `prepare_vk_bytes`:       Serialized Prepare verifying key (from setup())
 * - `prepare_instance_bytes`: Serialized Prepare instance (from present())
 * - `show_proof_bytes`:       Serialized Show proof (from present())
 * - `show_vk_bytes`:          Serialized Show verifying key (from setup())
 * - `show_instance_bytes`:    Serialized Show instance (from present())
 *
 * Returns: VerifyResult { valid, prepare_public_values, show_public_values, error? }
 */
export function verify(prepare_proof_bytes: Uint8Array, prepare_vk_bytes: Uint8Array, prepare_instance_bytes: Uint8Array, show_proof_bytes: Uint8Array, show_vk_bytes: Uint8Array, show_instance_bytes: Uint8Array): any;

/**
 * Verify a single proof (use verify() instead)
 */
export function verify_single(proof_bytes: Uint8Array, vk_bytes: Uint8Array): any;

export type InitInput = RequestInfo | URL | Response | BufferSource | WebAssembly.Module;

export interface InitOutput {
    readonly memory: WebAssembly.Memory;
    readonly compare_comm_w_shared: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly init: () => void;
    readonly precompute: (a: number, b: number) => [number, number, number];
    readonly precompute_from_witness: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly precompute_show_from_witness: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly present: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number];
    readonly setup: () => [number, number, number];
    readonly setup_prepare: () => [number, number, number];
    readonly setup_show: () => [number, number, number];
    readonly verify: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => [number, number, number];
    readonly verify_single: (a: number, b: number, c: number, d: number) => [number, number, number];
    readonly __wbindgen_malloc: (a: number, b: number) => number;
    readonly __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
    readonly __wbindgen_exn_store: (a: number) => void;
    readonly __externref_table_alloc: () => number;
    readonly __wbindgen_externrefs: WebAssembly.Table;
    readonly __wbindgen_free: (a: number, b: number, c: number) => void;
    readonly __externref_table_dealloc: (a: number) => void;
    readonly __wbindgen_start: () => void;
}

export type SyncInitInput = BufferSource | WebAssembly.Module;

/**
 * Instantiates the given `module`, which can either be bytes or
 * a precompiled `WebAssembly.Module`.
 *
 * @param {{ module: SyncInitInput }} module - Passing `SyncInitInput` directly is deprecated.
 *
 * @returns {InitOutput}
 */
export function initSync(module: { module: SyncInitInput } | SyncInitInput): InitOutput;

/**
 * If `module_or_path` is {RequestInfo} or {URL}, makes a request and
 * for everything else, calls `WebAssembly.instantiate` directly.
 *
 * @param {{ module_or_path: InitInput | Promise<InitInput> }} module_or_path - Passing `InitInput` directly is deprecated.
 *
 * @returns {Promise<InitOutput>}
 */
export default function __wbg_init (module_or_path?: { module_or_path: InitInput | Promise<InitInput> } | InitInput | Promise<InitInput>): Promise<InitOutput>;
