// auto-generated by circomkit
pragma circom 2.2.3;

include "../swiyu-age18-status.circom";

component main {public[issuerPubKeyX, issuerPubKeyY, challengeHash, cutoffDate, currentTime, expectedMetadataHashHi, expectedMetadataHashLo, expectedStatusSnapshotHashHi, expectedStatusSnapshotHashLo]} = SwiyuAge18Status(1920, 256, 1600, 17, 1, 1, 0);
