// auto-generated by circomkit
pragma circom 2.2.3;

include "../swiyu-age25-jwt.circom";

component main {public[issuerPubKeyX, issuerPubKeyY, nowDate, challengeHash]} = SwiyuAge25Jwt(1920, 256, 1600);
